<?php echo $this->doctype();?>

<html lang="en">
  <head>
    <?php echo $this->headTitle();?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php echo $this->headMeta();?>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css" rel="stylesheet">
    <?php echo $this->headLink();?>
  </head>
  <body style="padding-top:50px;">
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">ZF2x Application</a>
        </div>
        <div class="collapse navbar-collapse">
            <?php echo $this->navigation('user-menu')->menu()->setUlClass("nav navbar-nav navbar-right");?>
        </div>
      </div>
    </div>
    <?php echo $this->content;?>
    <?php echo $this->headScript();?>
    <?php echo $this->inlineScript();?>
  </body>
</html>
